apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugger
  labels:
    app: debugger
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: debugger
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: debugger
    spec:
      serviceAccountName: debugger
      initContainers:
      - name: sysctl
        image: quay.io/giantswarm/alpine:3.9-giantswarm-sysctl
        command:
        - sh
        - -c
        - sudo sysctl -w vm.swappiness=75
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 250m
            memory: 50Mi
      containers:
      - name: alpine
        image: quay.io/giantswarm/alpine:3.9-giantswarm-sysctl
        command:
        - sleep
        args:
        - 10h
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 250Mi
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
