apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: debug-network-policy
spec:
  podSelector:
    matchLabels:
      app: debug
  egress:
  - {}
  ingress:
  - {}
  policyTypes:
  - Egress
  - Ingress
