apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: debugger-network-policy
spec:
  podSelector:
    matchLabels:
      app: debugger
  egress:
  - {}
  ingress:
  - {}
  policyTypes:
  - Egress
  - Ingress
