apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: debugger-psp
spec:
  allowPrivilegeEscalation: true
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  privileged: true
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  runAsGroup:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 1
        max: 65535
  volumes:
  - '*'
