kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wealdy-debug-psp:restricted
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - wealdy-debug-psp
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: wealdy-debug-psp:restricted
subjects:
- kind: Group
  name: system:authenticated
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: wealdy-debug-psp:restricted
  apiGroup: rbac.authorization.k8s.io
