kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: debugger-psp:restricted
rules:
- apiGroups:
  - extensions
  resources:
  - podsecuritypolicies
  resourceNames:
  - debugger-psp
  verbs:
  - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: debugger-psp:restricted
subjects:
- kind: ServiceAccount
  name: debugger
  namespace: default
roleRef:
  kind: ClusterRole
  name: debugger-psp:restricted
  apiGroup: rbac.authorization.k8s.io

